# Generated by Django 4.1.5 on 2023-02-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.FileField(null=True, upload_to='receipts'),
        ),
    ]
